# Generated by Django 5.1.6 on 2025-02-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateField(auto_now_add=True, default='2025-02-13'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, default='Applied', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
